server:
  port: 8099

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: 29a13bd4-a24f-4c55-920e-699c8f543d50
      config:
        import-check:
          enabled: false
    gateway:
      routes:
        - id: atm
          uri: lb://atm
          predicates:
            - Path=/**
#        filters:
#          - RewritePath=/atm/(?<segment), /${segment}
