server:
  port: 8003
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enable: true

logging:
  level:
    root: info
    bob.homework: DEBUG
    org.springframework.cloud.loadbalancer: debug

feign:
  client:
    config:
      consumer:
        loggerLevel: full
#        request-interceptors:
#          - bob.homework.atm.feign.

spring:
  application:
    name: consumer
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: 29a13bd4-a24f-4c55-920e-699c8f543d50
      config:
        import-check:
          enabled: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: bob.homework.atm.mybatis.entity
